"""update

Revision ID: 661b90dcb396
Revises: 
Create Date: 2026-01-23 20:54:19.243470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '661b90dcb396'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=225), nullable=True),
    sa.Column('last_name', sa.String(length=225), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.Enum('SIPUNI', 'BINOTEL', name='provider_enum'), nullable=False),
    sa.Column('provider_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_companies_provider_type'), 'companies', ['provider_type'], unique=False)
    op.create_index(op.f('ix_companies_subdomain'), 'companies', ['subdomain'], unique=True)
    op.create_index(op.f('ix_companies_webhook_token'), 'companies', ['webhook_token'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_tag_name')
    )
    op.create_index('idx_tags_company_id', 'tags', ['company_id'], unique=False)
    op.create_index(op.f('ix_tags_company_id'), 'tags', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=225), nullable=False),
    sa.Column('last_name', sa.String(length=225), nullable=True),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=225), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'COMPANY_ADMIN', 'COMPANY_MANAGER', 'COMPANY_OPERATOR', name='role_enum'), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_company_email')
    )
    op.create_index('idx_users_company_id', 'users', ['company_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_company_id', 'audit_logs', ['company_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contacts_assigned_to', 'contacts', ['assigned_to'], unique=False)
    op.create_index('idx_contacts_company_id', 'contacts', ['company_id'], unique=False)
    op.create_index('idx_contacts_created_by', 'contacts', ['created_by'], unique=False)
    op.create_index('idx_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('idx_contacts_phone', 'contacts', ['phone'], unique=False)
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_company_id', 'notes', ['company_id'], unique=False)
    op.create_index('idx_notes_created_by', 'notes', ['created_by'], unique=False)
    op.create_index('idx_notes_entity', 'notes', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_notes_company_id'), 'notes', ['company_id'], unique=False)
    op.create_table('sipuni',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('cabinet_id', sa.String(length=25), nullable=False),
    sa.Column('security_key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('partner_contact', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id', 'cabinet_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='task_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='task_priority_enum'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False)
    op.create_index('idx_tasks_company_id', 'tasks', ['company_id'], unique=False)
    op.create_index('idx_tasks_created_by', 'tasks', ['created_by'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_entity', 'tasks', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'LOST', name='lead_status_enum'), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('NEW', 'CONTACT_MADE', 'MEETING_SCHEDULED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', name='pipeline_stage_enum'), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('idx_leads_company_id', 'leads', ['company_id'], unique=False)
    op.create_index('idx_leads_contact_id', 'leads', ['contact_id'], unique=False)
    op.create_index('idx_leads_pipeline_stage', 'leads', ['pipeline_stage'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_table('sipuni_call_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=False),
    sa.Column('call_start_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('call_end_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('sipuni_id', sa.UUID(), nullable=False),
    sa.Column('pbxdstnum', sa.String(length=255), nullable=False),
    sa.Column('dst_type', sa.String(length=1), nullable=False),
    sa.Column('src_num', sa.String(length=255), nullable=False),
    sa.Column('src_type', sa.String(length=1), nullable=False),
    sa.Column('last_called', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('transfer_from', sa.String(length=255), nullable=True),
    sa.Column('tree_number', sa.String(length=255), nullable=True),
    sa.Column('record_link', sa.String(length=2048), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ANSWER', 'BUSY', 'NOANSWER', 'CANCEL', 'CONGESTION', 'CHANUNAVAIL', name='callstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sipuni_id'], ['sipuni.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('stage', sa.Enum('PROSPECTING', 'QUALIFICATION', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST', name='deal_stage_enum'), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deals_assigned_to', 'deals', ['assigned_to'], unique=False)
    op.create_index('idx_deals_company_id', 'deals', ['company_id'], unique=False)
    op.create_index('idx_deals_contact_id', 'deals', ['contact_id'], unique=False)
    op.create_index('idx_deals_lead_id', 'deals', ['lead_id'], unique=False)
    op.create_index('idx_deals_stage', 'deals', ['stage'], unique=False)
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('SIPUNI', 'BINOTEL', name='provider_enum'), nullable=False),
    sa.Column('provider_call_id', sa.String(length=255), nullable=False),
    sa.Column('phone_1', sa.String(length=50), nullable=True),
    sa.Column('phone_2', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', 'INTERNAL', name='call_direction_enum'), nullable=True),
    sa.Column('state', sa.Enum('ANSWER', 'BUSY', 'NOANSWER', 'CANCEL', 'CONGESTION', 'CHANUNAVAIL', name='call_status_enum'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('waiting_sec', sa.Integer(), nullable=True),
    sa.Column('billing_sec', sa.Integer(), nullable=True),
    sa.Column('record_url', sa.Text(), nullable=True),
    sa.Column('call_start_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('call_end_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.Enum('INTERESTED', 'APPOINTMENT_SCHEDULED', 'FOLLOW_UP', 'SALE_MADE', 'NO_ANSWER', 'LEFT_VOICEMAIL', 'BUSY', 'CALLBACK_REQUESTED', 'INFORMATION_PROVIDED', 'NOT_INTERESTED', 'WRONG_NUMBER', 'DO_NOT_CALL', 'CUSTOMER_COMPLAINT', 'OTHER', name='call_outcome_enum'), nullable=True),
    sa.Column('disposition_notes', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('company_number', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'provider_type', 'provider_call_id', name='uq_company_provider_call')
    )
    op.create_index('idx_call_events_company_id', 'call_events', ['company_id'], unique=False)
    op.create_index('idx_call_events_contact_id', 'call_events', ['contact_id'], unique=False)
    op.create_index('idx_call_events_created_at', 'call_events', ['created_at'], unique=False)
    op.create_index('idx_call_events_lead_id', 'call_events', ['lead_id'], unique=False)
    op.create_index('idx_call_events_operator_id', 'call_events', ['operator_id'], unique=False)
    op.create_index('idx_call_events_phone_1', 'call_events', ['phone_1'], unique=False)
    op.create_index('idx_call_events_phone_2', 'call_events', ['phone_2'], unique=False)
    op.create_index(op.f('ix_call_events_company_id'), 'call_events', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_events_company_id'), table_name='call_events')
    op.drop_index('idx_call_events_phone_2', table_name='call_events')
    op.drop_index('idx_call_events_phone_1', table_name='call_events')
    op.drop_index('idx_call_events_operator_id', table_name='call_events')
    op.drop_index('idx_call_events_lead_id', table_name='call_events')
    op.drop_index('idx_call_events_created_at', table_name='call_events')
    op.drop_index('idx_call_events_contact_id', table_name='call_events')
    op.drop_index('idx_call_events_company_id', table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_index('idx_deals_stage', table_name='deals')
    op.drop_index('idx_deals_lead_id', table_name='deals')
    op.drop_index('idx_deals_contact_id', table_name='deals')
    op.drop_index('idx_deals_company_id', table_name='deals')
    op.drop_index('idx_deals_assigned_to', table_name='deals')
    op.drop_table('deals')
    op.drop_table('sipuni_call_events')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_pipeline_stage', table_name='leads')
    op.drop_index('idx_leads_contact_id', table_name='leads')
    op.drop_index('idx_leads_company_id', table_name='leads')
    op.drop_index('idx_leads_assigned_to', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_entity', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_created_by', table_name='tasks')
    op.drop_index('idx_tasks_company_id', table_name='tasks')
    op.drop_index('idx_tasks_assigned_to', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('sipuni')
    op.drop_index(op.f('ix_notes_company_id'), table_name='notes')
    op.drop_index('idx_notes_entity', table_name='notes')
    op.drop_index('idx_notes_created_by', table_name='notes')
    op.drop_index('idx_notes_company_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_index('idx_contacts_phone', table_name='contacts')
    op.drop_index('idx_contacts_email', table_name='contacts')
    op.drop_index('idx_contacts_created_by', table_name='contacts')
    op.drop_index('idx_contacts_company_id', table_name='contacts')
    op.drop_index('idx_contacts_assigned_to', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_company_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_company_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_company_id'), table_name='tags')
    op.drop_index('idx_tags_company_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_companies_webhook_token'), table_name='companies')
    op.drop_index(op.f('ix_companies_subdomain'), table_name='companies')
    op.drop_index(op.f('ix_companies_provider_type'), table_name='companies')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
