"""add_contracts_table

Revision ID: 848cafadb806
Revises: add_composite_indexes
Create Date: 2026-02-09 00:45:01.232924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '848cafadb806'
down_revision: Union[str, None] = 'add_composite_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_admins', sa.Integer(), nullable=False),
    sa.Column('max_managers', sa.Integer(), nullable=False),
    sa.Column('max_operators', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'YEARLY', name='billing_period_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WARNING', 'GRACE_PERIOD', 'EXPIRED', 'SUSPENDED', 'CANCELLED', name='contract_status_enum'), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'PENDING', 'OVERDUE', 'FAILED', name='payment_status_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contracts_company_id', 'contracts', ['company_id'], unique=False)
    op.create_index('idx_contracts_end_date', 'contracts', ['end_date'], unique=False)
    op.create_index('idx_contracts_owner_id', 'contracts', ['owner_id'], unique=False)
    op.create_index('idx_contracts_status', 'contracts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contracts_status', table_name='contracts')
    op.drop_index('idx_contracts_owner_id', table_name='contracts')
    op.drop_index('idx_contracts_end_date', table_name='contracts')
    op.drop_index('idx_contracts_company_id', table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
